### PR TITLE
Add additional package info to package.json

### PR DESCRIPTION
**Pull request by qualk**
Added a description, Solar Tweaks homepage URL, and bug URL to `package.json`. Nothing big. (Prior PR was deleted my me bc i wanted to rename the branch name).

### CODE REVIEW

**Comment by HypedDomi** [comment]
I will add it to the Dev Repo

**Comment by qualk** [comment]
> I will add it to the Dev Repo

:O ty @HypedDomi, I'll be working on the current ST version (mainly upgrading the dependencies & some code cleanup)

**Comment by qualk** [comment]
Should I close the PR?

**Comment by HypedDomi** [comment]
> Should I close the PR?

@TBHGodPro

**Comment by TBHGodPro** [comment]
Closed, @HypedDomi if your new branch works and you’ve tested the below, you can merge it to main v4-dev.

- Serves
- Builds
- Can run both served and built without any new errors in console

**Pull request closed without merging**
